/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service and database health */
        get: operations["read_health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sign-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account and sign in */
        post: operations["sign_up_api_v1_auth_sign_up_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with email and password */
        post: operations["sign_in_api_v1_auth_sign_in_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in to the shared demo account */
        post: operations["sign_in_demo_api_v1_auth_demo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out */
        post: operations["sign_out_api_v1_auth_sign_out_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user */
        get: operations["read_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosted-zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search, sort and page your hosted zones */
        get: operations["list_hosted_zones_api_v1_hosted_zones_get"];
        put?: never;
        /** Create a hosted zone with its default NS and SOA records */
        post: operations["create_hosted_zone_api_v1_hosted_zones_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosted-zones/{zone_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one hosted zone */
        get: operations["get_hosted_zone_api_v1_hosted_zones__zone_id__get"];
        put?: never;
        post?: never;
        /** Delete a zone that has only its default NS and SOA records */
        delete: operations["delete_hosted_zone_api_v1_hosted_zones__zone_id__delete"];
        options?: never;
        head?: never;
        /** Edit a zone's comment */
        patch: operations["update_hosted_zone_api_v1_hosted_zones__zone_id__patch"];
        trace?: never;
    };
    "/api/v1/hosted-zones/{zone_id}/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search, filter and page record sets */
        get: operations["list_record_sets_api_v1_hosted_zones__zone_id__records_get"];
        put?: never;
        /** Create Record Set */
        post: operations["create_record_set_api_v1_hosted_zones__zone_id__records_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosted-zones/{zone_id}/records/import/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Bind Import */
        post: operations["preview_bind_import_api_v1_hosted_zones__zone_id__records_import_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosted-zones/{zone_id}/records/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply Bind Import */
        post: operations["apply_bind_import_api_v1_hosted_zones__zone_id__records_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosted-zones/{zone_id}/records/{record_set_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Record Set */
        get: operations["get_record_set_api_v1_hosted_zones__zone_id__records__record_set_id__get"];
        /** Update Record Set */
        put: operations["update_record_set_api_v1_hosted_zones__zone_id__records__record_set_id__put"];
        post?: never;
        /** Delete Record Set */
        delete: operations["delete_record_set_api_v1_hosted_zones__zone_id__records__record_set_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BindImportPreview */
        BindImportPreview: {
            /** File Name */
            file_name: string;
            /** Records */
            records: components["schemas"]["BindImportRecord"][];
            /** Add Count */
            add_count: number;
            /** Already Present Count */
            already_present_count: number;
            /** Unsupported Count */
            unsupported_count: number;
        };
        /** BindImportRecord */
        BindImportRecord: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Ttl */
            ttl: number;
            /** Values */
            values: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "add" | "already_present" | "unsupported";
            /** Reason */
            reason?: string | null;
        };
        /** BindImportResult */
        BindImportResult: {
            /** Imported Count */
            imported_count: number;
            /** Skipped Count */
            skipped_count: number;
        };
        /** Body_apply_bind_import_api_v1_hosted_zones__zone_id__records_import_post */
        Body_apply_bind_import_api_v1_hosted_zones__zone_id__records_import_post: {
            /** File */
            file: string;
        };
        /** Body_preview_bind_import_api_v1_hosted_zones__zone_id__records_import_preview_post */
        Body_preview_bind_import_api_v1_hosted_zones__zone_id__records_import_preview_post: {
            /** File */
            file: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Environment */
            environment: string;
            /** Database */
            database: string;
        };
        /**
         * HostedZoneCreate
         * @example {
         *       "comment": "Production zone",
         *       "name": "example.com",
         *       "private_zone": false
         *     }
         * @example {
         *       "name": "internal.example.com",
         *       "private_zone": true,
         *       "vpc": {
         *         "region": "us-east-1",
         *         "vpc_id": "vpc-0a1b2c3d"
         *       }
         *     }
         */
        HostedZoneCreate: {
            /**
             * Name
             * @description Domain name. Case, a trailing dot and surrounding spaces don't matter.
             */
            name: string;
            /** Comment */
            comment?: string | null;
            /**
             * Private Zone
             * @default false
             */
            private_zone: boolean;
            /** @description Required for private zones only. */
            vpc?: components["schemas"]["Vpc"] | null;
            /** Tags */
            tags?: components["schemas"]["HostedZoneTag"][];
        };
        /**
         * HostedZoneDetail
         * @example {
         *       "comment": "Production zone",
         *       "created_at": "2026-10-01T12:00:00Z",
         *       "id": "Z0812345ABCDEFGHIJKLM",
         *       "name": "example.com.",
         *       "name_servers": [
         *         "ns-1234.awsdns-26.org.",
         *         "ns-567.awsdns-06.net.",
         *         "ns-1789.awsdns-31.co.uk.",
         *         "ns-89.awsdns-11.com."
         *       ],
         *       "private_zone": false,
         *       "record_count": 2,
         *       "updated_at": "2026-10-01T12:00:00Z"
         *     }
         */
        HostedZoneDetail: {
            /**
             * Id
             * @description Route 53 style hosted zone ID.
             */
            id: string;
            /**
             * Name
             * @description Fully qualified domain name, with the trailing dot.
             */
            name: string;
            /** Comment */
            comment: string | null;
            /** Private Zone */
            private_zone: boolean;
            /**
             * Record Count
             * @description Record sets in the zone, including NS and SOA.
             */
            record_count: number;
            /** Tags */
            tags?: components["schemas"]["HostedZoneTag"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Name Servers
             * @description The four servers Route 53 assigned.
             */
            name_servers: string[];
            vpc: components["schemas"]["Vpc"] | null;
        };
        /** HostedZoneList */
        HostedZoneList: {
            /** Items */
            items: components["schemas"]["HostedZoneOut"][];
            /**
             * Total
             * @description Number of hosted zones matching the request.
             */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * HostedZoneOut
         * @example {
         *       "comment": "Production zone",
         *       "created_at": "2026-10-01T12:00:00Z",
         *       "id": "Z0812345ABCDEFGHIJKLM",
         *       "name": "example.com.",
         *       "private_zone": false,
         *       "record_count": 2
         *     }
         */
        HostedZoneOut: {
            /**
             * Id
             * @description Route 53 style hosted zone ID.
             */
            id: string;
            /**
             * Name
             * @description Fully qualified domain name, with the trailing dot.
             */
            name: string;
            /** Comment */
            comment: string | null;
            /** Private Zone */
            private_zone: boolean;
            /**
             * Record Count
             * @description Record sets in the zone, including NS and SOA.
             */
            record_count: number;
            /** Tags */
            tags?: components["schemas"]["HostedZoneTag"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HostedZoneTag */
        HostedZoneTag: {
            /** Key */
            key: string;
            /**
             * Value
             * @default
             */
            value: string;
        };
        /**
         * HostedZoneUpdate
         * @description Route 53 only lets a zone's comment change after it is created.
         */
        HostedZoneUpdate: {
            /** Comment */
            comment: string | null;
            /** Tags */
            tags?: components["schemas"]["HostedZoneTag"][] | null;
        };
        /** RecordSetCreate */
        RecordSetCreate: {
            /**
             * Name
             * @description A name relative to the zone, an absolute name, or @ for the zone apex.
             * @example www
             */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "A" | "AAAA" | "CNAME" | "TXT" | "MX" | "NS" | "PTR" | "SRV" | "CAA";
            /**
             * Ttl
             * @example 300
             */
            ttl: number | null;
            /** Values */
            values: string[];
            /**
             * Routing Policy
             * @default simple
             * @enum {string}
             */
            routing_policy: "simple" | "weighted" | "failover" | "latency" | "geolocation" | "multivalue";
            /** Set Identifier */
            set_identifier?: string | null;
            /** Weight */
            weight?: number | null;
            /** Failover Role */
            failover_role?: ("PRIMARY" | "SECONDARY") | null;
            /** Region */
            region?: string | null;
            /** Geolocation */
            geolocation?: string | null;
            /**
             * Alias
             * @default false
             */
            alias: boolean;
            /** Alias Target Type */
            alias_target_type?: ("cloudfront" | "s3-website" | "load-balancer" | "api-gateway" | "record") | null;
            /** Alias Target */
            alias_target?: string | null;
            /**
             * Evaluate Target Health
             * @default false
             */
            evaluate_target_health: boolean;
        };
        /** RecordSetList */
        RecordSetList: {
            /** Items */
            items: components["schemas"]["RecordSetOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** RecordSetOut */
        RecordSetOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "A" | "AAAA" | "CNAME" | "TXT" | "MX" | "NS" | "PTR" | "SRV" | "CAA" | "SOA";
            /** Ttl */
            ttl: number | null;
            /** Values */
            values: string[];
            /**
             * Routing Policy
             * @enum {string}
             */
            routing_policy: "simple" | "weighted" | "failover" | "latency" | "geolocation" | "multivalue";
            /** Set Identifier */
            set_identifier: string | null;
            /** Weight */
            weight: number | null;
            /** Failover Role */
            failover_role: ("PRIMARY" | "SECONDARY") | null;
            /** Region */
            region: string | null;
            /** Geolocation */
            geolocation: string | null;
            /** Alias */
            alias: boolean;
            /** Alias Target Type */
            alias_target_type: ("cloudfront" | "s3-website" | "load-balancer" | "api-gateway" | "record") | null;
            /** Alias Target */
            alias_target: string | null;
            /** Evaluate Target Health */
            evaluate_target_health: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RecordSetUpdate */
        RecordSetUpdate: {
            /**
             * Name
             * @description A name relative to the zone, an absolute name, or @ for the zone apex.
             * @example www
             */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "A" | "AAAA" | "CNAME" | "TXT" | "MX" | "NS" | "PTR" | "SRV" | "CAA";
            /**
             * Ttl
             * @example 300
             */
            ttl: number | null;
            /** Values */
            values: string[];
            /**
             * Routing Policy
             * @default simple
             * @enum {string}
             */
            routing_policy: "simple" | "weighted" | "failover" | "latency" | "geolocation" | "multivalue";
            /** Set Identifier */
            set_identifier?: string | null;
            /** Weight */
            weight?: number | null;
            /** Failover Role */
            failover_role?: ("PRIMARY" | "SECONDARY") | null;
            /** Region */
            region?: string | null;
            /** Geolocation */
            geolocation?: string | null;
            /**
             * Alias
             * @default false
             */
            alias: boolean;
            /** Alias Target Type */
            alias_target_type?: ("cloudfront" | "s3-website" | "load-balancer" | "api-gateway" | "record") | null;
            /** Alias Target */
            alias_target?: string | null;
            /**
             * Evaluate Target Health
             * @default false
             */
            evaluate_target_health: boolean;
        };
        /** SignInRequest */
        SignInRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * SignUpRequest
         * @example {
         *       "email": "you@example.com",
         *       "password": "a long password"
         *     }
         */
        SignUpRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** UserOut */
        UserOut: {
            /** Email */
            email: string;
            /**
             * Account Id
             * @description Mocked 12-digit AWS account ID.
             */
            account_id: string;
            /** Is Demo */
            is_demo: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Vpc
         * @description A mocked VPC. Nothing is looked up; the values only have to look right.
         */
        Vpc: {
            /**
             * Region
             * @example us-east-1
             * @enum {string}
             */
            region: "us-east-1" | "us-east-2" | "us-west-1" | "us-west-2" | "af-south-1" | "ap-east-1" | "ap-south-1" | "ap-south-2" | "ap-northeast-1" | "ap-northeast-2" | "ap-northeast-3" | "ap-southeast-1" | "ap-southeast-2" | "ap-southeast-3" | "ca-central-1" | "eu-central-1" | "eu-central-2" | "eu-west-1" | "eu-west-2" | "eu-west-3" | "eu-north-1" | "eu-south-1" | "me-south-1" | "me-central-1" | "sa-east-1";
            /**
             * Vpc Id
             * @example vpc-0a1b2c3d
             */
            vpc_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    sign_up_api_v1_auth_sign_up_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_in_api_v1_auth_sign_in_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_in_demo_api_v1_auth_demo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    sign_out_api_v1_auth_sign_out_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    read_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    list_hosted_zones_api_v1_hosted_zones_get: {
        parameters: {
            query?: {
                /** @description Case-insensitive text to find in the name, ID or comment. */
                q?: string | null;
                tag_key?: string | null;
                tag_value?: string | null;
                /** @description Prefix with - for descending. */
                sort?: "name" | "-name" | "type" | "-type" | "record_count" | "-record_count" | "created_at" | "-created_at";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostedZoneList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_hosted_zone_api_v1_hosted_zones_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HostedZoneCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostedZoneDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_hosted_zone_api_v1_hosted_zones__zone_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostedZoneDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_hosted_zone_api_v1_hosted_zones__zone_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The zone still has other record sets. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_hosted_zone_api_v1_hosted_zones__zone_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HostedZoneUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostedZoneDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_record_sets_api_v1_hosted_zones__zone_id__records_get: {
        parameters: {
            query?: {
                /** @description Case-insensitive text to find in the record name or value. */
                q?: string | null;
                type?: ("A" | "AAAA" | "CNAME" | "TXT" | "MX" | "NS" | "PTR" | "SRV" | "CAA" | "SOA") | null;
                routing_policy?: ("simple" | "weighted" | "failover" | "latency" | "geolocation" | "multivalue") | null;
                sort?: "name" | "-name" | "type" | "-type" | "ttl" | "-ttl";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordSetList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_record_set_api_v1_hosted_zones__zone_id__records_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordSetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordSetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_bind_import_api_v1_hosted_zones__zone_id__records_import_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_preview_bind_import_api_v1_hosted_zones__zone_id__records_import_preview_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BindImportPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_bind_import_api_v1_hosted_zones__zone_id__records_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_apply_bind_import_api_v1_hosted_zones__zone_id__records_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BindImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_record_set_api_v1_hosted_zones__zone_id__records__record_set_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                zone_id: string;
                record_set_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordSetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_record_set_api_v1_hosted_zones__zone_id__records__record_set_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                zone_id: string;
                record_set_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordSetUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordSetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_record_set_api_v1_hosted_zones__zone_id__records__record_set_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                zone_id: string;
                record_set_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
